### ISSUE TITLE
Issue with M1 Mac or just me?

### ISSUE THREAD

**Issue by trsneed** [lokalise/lokalise-cli-2-go#75]
I wound up opening iTerm in Rosetta to install the CLI, that allowed `brew tap lokalise/cli-2` to run without issue, however when I run `brew install lokalise2` I get the following:

```
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

Without rosetta running on iTerm, I get a different issue 
```
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:274:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:209:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:181:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:181:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:412:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:636:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:632:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:632:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:311:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:131:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

I suspect I am doing something wrong but could use a bit of guidance!

**Comment by andrewLab-lokalise** [comment]
Hey, @trsneed. Just released a new version with binaries for M1. Could you please retry?

**Comment by trsneed** [comment]
Seems to work! Thanks a ton!
